(function () {
    const currentHost = window.location.hostname.toLowerCase().replace('www.', ''); let overlayElement = null; let timerInterval = null; let trackingInterval = null; let trackingSeconds = 0; const QUOTES = [{ text: "The only way to do great work is to love what you do.", author: "Steve Jobs" }, { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" }, { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" }, { text: "Where focus goes, energy flows.", author: "Tony Robbins" }, { text: "Starve your distractions, feed your focus.", author: "Unknown" }, { text: "Concentrate all your thoughts upon the work at hand.", author: "Alexander Graham Bell" }, { text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Einstein" }, { text: "The best way to predict the future is to create it.", author: "Peter Drucker" }];
    function startTimeTracking() { if (trackingInterval) return; trackingInterval = setInterval(() => { trackingSeconds += 5; if (trackingSeconds >= 30) { chrome.runtime.sendMessage({ cmd: 'TRACK_TIME', domain: currentHost, seconds: trackingSeconds }); trackingSeconds = 0; } }, 5000); }
    function stopTimeTracking() { if (trackingInterval) { clearInterval(trackingInterval); trackingInterval = null; if (trackingSeconds > 0) { chrome.runtime.sendMessage({ cmd: 'TRACK_TIME', domain: currentHost, seconds: trackingSeconds }); trackingSeconds = 0; } } }
    function checkBlocking(data) { if (!data.isRunning) return false; if (data.enabled === false) return false; const whitelistMode = data.whitelistMode || false; const listToCheck = whitelistMode ? (data.whitelist || []) : (data.blocklist || []); const isInList = listToCheck.some(domain => { const cleanDomain = domain.trim().toLowerCase().replace('www.', ''); return currentHost.includes(cleanDomain) || cleanDomain.includes(currentHost); }); return whitelistMode ? !isInList : isInList; }
    function formatTime(seconds) { if (!seconds || seconds < 0) seconds = 0; const m = Math.floor(seconds / 60); const s = seconds % 60; return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`; }
    function getRandomQuote() { return QUOTES[Math.floor(Math.random() * QUOTES.length)]; }
    function injectBlockOverlay(domain, initialTime) { window.stop(); stopTimeTracking(); const quote = getRandomQuote(); overlayElement = document.createElement('div'); overlayElement.id = 'focus-minimal-blocker'; overlayElement.innerHTML = `<style>#focus-minimal-blocker{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;background:#121212!important;z-index:2147483647!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif!important;color:white!important}#focus-minimal-blocker .icon{font-size:80px;margin-bottom:20px;animation:pulse 2s infinite}@keyframes pulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.1);opacity:0.8}}#focus-minimal-blocker h1{font-size:42px!important;margin:0 0 10px 0!important;font-weight:700!important}#focus-minimal-blocker .domain{font-size:20px!important;opacity:0.7!important;margin-bottom:30px!important;padding:10px 20px!important;background:rgba(255,255,255,0.1)!important;border-radius:8px!important}#focus-minimal-blocker .timer-display{font-size:64px!important;font-weight:700!important;margin:20px 0!important;font-family:monospace!important;background:rgba(124,77,255,0.3)!important;padding:20px 40px!important;border-radius:16px!important;border:2px solid rgba(124,77,255,0.5)!important}#focus-minimal-blocker .quote{max-width:500px!important;text-align:center!important;margin-top:30px!important;padding:20px!important;background:rgba(255,255,255,0.05)!important;border-radius:12px!important;border-left:4px solid rgba(124,77,255,0.6)!important}#focus-minimal-blocker .quote-text{font-size:18px!important;font-style:italic!important;line-height:1.6!important;opacity:0.9!important}#focus-minimal-blocker .quote-author{margin-top:10px!important;font-size:14px!important;opacity:0.6!important}#focus-minimal-blocker .hint{margin-top:25px!important;font-size:14px!important;opacity:0.5!important}</style><div class="icon"><svg viewBox="0 0 24 24" width="80" height="80" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" style="color: #7c4dff;"><circle cx="12" cy="12" r="10"></circle><line x1="15" y1="9" x2="9" y2="15"></line><line x1="9" y1="9" x2="15" y2="15"></line></svg></div><h1>Focus Mode Active</h1><div class="domain">${domain}</div><div class="timer-display" id="blockTimer">${formatTime(initialTime)}</div><div class="quote"><div class="quote-text">"${quote.text}"</div><div class="quote-author">- ${quote.author}</div></div><div class="hint">Stay focused! This site will unblock when the timer ends.</div>`; document.documentElement.innerHTML = ''; document.documentElement.appendChild(overlayElement); document.body.style.overflow = 'hidden'; startTimerSync(); }
    function startTimerSync() { timerInterval = setInterval(() => { chrome.storage.local.get(['timeLeft', 'isRunning'], (data) => { if (!data.isRunning) { removeOverlayAndReload(); return; } const timerEl = document.getElementById('blockTimer'); if (timerEl) { timerEl.textContent = formatTime(data.timeLeft); } }); }, 500); }
    function removeOverlayAndReload() { if (overlayElement) { if (timerInterval) { clearInterval(timerInterval); timerInterval = null; } window.location.reload(); } }
    chrome.storage.local.get(['isRunning', 'blocklist', 'whitelist', 'enabled', 'timeLeft', 'whitelistMode'], (data) => { if (checkBlocking(data)) { injectBlockOverlay(currentHost, data.timeLeft); } else { startTimeTracking(); } });
    chrome.storage.onChanged.addListener((changes, namespace) => { if (changes.isRunning || changes.enabled) { chrome.storage.local.get(['isRunning', 'enabled', 'blocklist', 'whitelist', 'whitelistMode', 'timeLeft'], (data) => { if (data.isRunning === false || data.enabled === false) { removeOverlayAndReload(); } else if (data.isRunning === true && data.enabled === true) { if (checkBlocking(data) && !overlayElement) { injectBlockOverlay(currentHost, data.timeLeft); } } }); } });
    window.addEventListener('beforeunload', stopTimeTracking);
})();
